#!/usr/bin/env python3
"""program.py — collect rendered primitives into one tpulang program.

A :class:`Program` is an ordered list of blocks. Each block is one rendered
primitive; concatenating them and appending ``halt`` gives a single ``.tpu``
source that the *existing* toolchain handles with no changes — ``assembler.py``
assembles it, ``iss.py`` runs it, ``tpu_top_tb.sv`` can execute the vectors it
emits.

**The generated ``.tpu`` is the artifact**, not an intermediate. It comes out
with a banner per block naming the primitive and the shapes it was instantiated
with, so it can be read, diffed, hand-edited and assembled on its own. A
generator whose output you cannot read is a generator you cannot debug against a
bitstream.

The one budget worth watching is instruction memory: ``IMEM_AW = 10``, so **1024
words**, and the ISA has no call/return — every instantiation is inlined.
:meth:`Program.finalize` asserts on the limit and :meth:`Program.report` prints
the per-block breakdown, because "which primitive is eating the program" is the
question you actually need answered when it overflows.
"""

from __future__ import annotations

import os
import sys
from dataclasses import dataclass, field

_HERE = os.path.dirname(os.path.abspath(__file__))
for _p in (_HERE, os.path.dirname(_HERE)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

import gen_vectors as gv                                        # noqa: E402
from assembler import AsmError, Assembler                       # noqa: E402
from iss import TPU                                             # noqa: E402

IMEM_WORDS = 1 << 10        # tpu_top.sv IMEM_AW = 10


class ProgramError(Exception):
    """The program does not fit, or a block failed to assemble."""


@dataclass
class Block:
    name: str          # the instance prefix, e.g. 'mm_qkv'
    primitive: str
    note: str          # one line describing the instantiation, for the banner
    text: str
    words: int


@dataclass
class Program:
    """An ordered list of rendered primitives that assembles into one image."""

    name: str = "program"
    blocks: list = field(default_factory=list)
    arenas: list = field(default_factory=list)
    notes: list = field(default_factory=list)     # header comment lines

    source: str | None = field(default=None, init=False)
    words: list | None = field(default=None, init=False)
    consts: dict | None = field(default=None, init=False)

    # ---- construction --------------------------------------------------------

    def add(self, name: str, primitive: str, text: str, note: str = "") -> Block:
        """Append one rendered primitive. Names must be unique (they are the
        symbol-mangling prefix, so a duplicate would collide in the assembler)."""
        if any(b.name == name for b in self.blocks):
            raise ProgramError(f"duplicate block name '{name}'")
        blk = Block(name, primitive, note, text, _count_words(text, name))
        self.blocks.append(blk)
        self.source = self.words = None      # invalidate any previous finalize
        return blk

    def track(self, arena) -> None:
        """Register an arena so its tensors appear in the memory map / image."""
        self.arenas.append(arena)

    # ---- emit ----------------------------------------------------------------

    def render(self) -> str:
        """The full ``.tpu`` source, banners and all."""
        out = [
            f"; {'=' * 76}",
            f"; {self.name} — generated by accel/tpulang/pytpu. Do not edit by hand;",
            f"; edit the composer or the primitive templates under pytpu/lib/ instead.",
        ]
        out += [f"; {line}" for line in self.notes]
        out.append(f"; {'=' * 76}")
        for i, blk in enumerate(self.blocks):
            out += [
                "",
                f"; {'-' * 74}",
                f"; [{i}] {blk.primitive}  ({blk.name}){'  — ' + blk.note if blk.note else ''}",
                f"; {'-' * 74}",
                blk.text.rstrip("\n"),
            ]
        out += ["", "    halt", ""]
        return "\n".join(out)

    def finalize(self) -> list:
        """Assemble. Returns the instruction words; raises if it does not fit."""
        self.source = self.render()
        try:
            asm = Assembler()
            asm.scan(self.source)
            self.words = asm.encode_all()
        except AsmError as exc:
            raise ProgramError(f"{self.name}: {exc}") from None
        self.consts = asm.consts
        if len(self.words) > IMEM_WORDS:
            raise ProgramError(
                f"{self.name}: {len(self.words)} words exceeds instruction memory "
                f"({IMEM_WORDS} words, tpu_top.sv IMEM_AW = 10). The ISA has no "
                f"call/return, so every primitive is inlined: drop a block, or "
                f"hoist a repeated one into a runtime loop.\n" + self.report()
            )
        return self.words

    def emit_source(self, path: str) -> str:
        if self.source is None:
            self.finalize()
        os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(self.source)
        return path

    # ---- reporting -----------------------------------------------------------

    def report(self) -> str:
        total = sum(b.words for b in self.blocks) + 1        # + halt
        lines = ["block                          primitive           words   cum"]
        cum = 0
        for blk in self.blocks:
            cum += blk.words
            lines.append(f"  {blk.name:<28s} {blk.primitive:<18s} {blk.words:5d} "
                         f"{cum:5d}")
        pct = 100.0 * total / IMEM_WORDS
        lines.append(f"  {'':<28s} {'halt':<18s} {1:5d} {total:5d}")
        lines.append(f"  {'-' * 62}")
        lines.append(f"  {total} / {IMEM_WORDS} instruction words  ({pct:.0f}%)")
        return "\n".join(lines)

    def memory_map(self) -> str:
        return "\n\n".join(a.map() for a in self.arenas)

    # ---- host image / simulation ---------------------------------------------

    def host_image(self) -> dict:
        """``{addr: byte}`` for every tracked tensor that has ``data`` set.

        This is what the host would write into DRAM before starting the program
        (the testbench's ``tpu_spad_in.hex``, or ``run_program.py``'s ``W``
        commands).
        """
        img: dict = {}
        for arena in self.arenas:
            for t in arena.tensors:
                if t.data is None:
                    continue
                if len(t.data) != t.nbytes:
                    raise ProgramError(
                        f"tensor '{t.name}' has {len(t.data)} bytes of data but "
                        f"occupies {t.nbytes}")
                for k, byte in enumerate(t.data):
                    addr = t.addr + k
                    if addr in img:
                        raise ProgramError(
                            f"tensor '{t.name}' overlaps another at 0x{addr:04x}")
                    img[addr] = byte & 0xFF
        return img

    def run_iss(self, in_img: dict, max_steps: int = 5_000_000) -> tuple[dict, TPU]:
        """Run in the ISS over ``in_img``. Returns the spilled DRAM bytes.

        ``max_steps`` is well above ``iss.TPU.run``'s default: that default is
        sized for the straight-line examples, and a layer made of loop nests
        retires tens of thousands of instructions.
        """
        if self.words is None:
            self.finalize()
        tpu = TPU(rows=gv.ROWS, cols=gv.COLS, addr_w=gv.ADDR_W,
                  m0_w=gv.M0_W, n_w=gv.N_W)
        for addr, byte in in_img.items():
            tpu.dram[tpu._a(addr)] = byte & 0xFF
        tpu.run(self.words, max_steps=max_steps)
        return {a: tpu.dram[a] for a in sorted(tpu.dram_written)}, tpu

    def emit_vectors(self, out_dir: str, in_img: dict, out_img: dict) -> dict:
        """Write the three ``$readmemh`` files ``tpu_top_tb.sv`` loads.

        Same names and same format as ``gen_vectors.py`` (whose emitters are
        reused here), so the testbench runs a generated program unchanged.
        """
        os.makedirs(out_dir, exist_ok=True)
        paths = {
            "prog": os.path.join(out_dir, "tpu_prog.hex"),
            "in": os.path.join(out_dir, "tpu_spad_in.hex"),
            "exp": os.path.join(out_dir, "tpu_spad_exp.hex"),
        }
        gv.emit_words(paths["prog"], self.words,
                      f"instruction words generated by pytpu for {self.name}")
        gv.emit_bytes(paths["in"], in_img, f"input tensors for {self.name} (DRAM)")
        gv.emit_bytes(paths["exp"], out_img,
                      f"golden outputs for {self.name} (ISS-computed, DRAM)")
        return paths


def _count_words(text: str, name: str) -> int:
    """Instruction count of one block, by assembling it on its own.

    Blocks are self-contained — every ``.equ``, ``.reg`` and label they use is
    defined inside them — so a standalone scan resolves, and it catches a broken
    template at the block that broke rather than 600 lines later.
    """
    try:
        asm = Assembler()
        asm.scan(text)
        asm.encode_all()
    except AsmError as exc:
        raise ProgramError(f"block '{name}' does not assemble: {exc}") from None
    return len(asm.instrs)
